### ISSUE TITLE
500 Error when address is multiple lines

### ISSUE THREAD

**Issue by tingar** [google/personfinder#142]
When adding information about a person, if the address is more than 1 line, submitting the form results in a 500 error.

Error from the console log:
```
ERROR    2015-08-27 04:16:45,658 webapp2.py:1528] Property last_known_location is not multi-line
Traceback (most recent call last):

  File "personfinder/app/main.py", line 504, in serve
    getattr(handler, request.method.lower())()  # get() or post()
  File "personfinder/app/view.py", line 245, in post
    photo_url=photo_url)
  File "personfinder/app/model.py", line 223, in create_original
    return cls(key_name=repo + ':' + record_id, repo=repo, **kwargs)

BadValueError: Property last_known_location is not multi-line
INFO     2015-08-27 04:16:45,662 module.py:808] default: "POST /japan/view HTTP/1.1" 500 228
```

**Comment by gimite** [comment]
Thanks for the report. Fixed.
